Adding reset password.
Finish the following requirement.
```
Reset Password [Undone]
	Need to make sign up locally.
```

Reference:
google 'django post form'
https://docs.djangoproject.com/en/4.0/topics/forms/
google 'python django form password validation'
https://stackoverflow.com/questions/11679918/django-form-for-resetting-the-password
Get the keywords 'PasswordChangeForm' and google 'python django PasswordChangeForm'
https://www.programcreek.com/python/example/50650/django.contrib.auth.forms.PasswordChangeForm

google 'python django PasswordChangeForm custom validation'
https://sixfeetup.com/blog/custom-password-validators-in-django

https://auth0.com/docs/authenticate/database-connections/password-change
Used to change password by Auth0  APIs.

Error Hangling.
ImportError: cannot import name 'ugettext' from 'django.utils.translation'
https://stackoverflow.com/questions/71420362/django4-0-importerror-cannot-import-name-ugettext-lazy-from-django-utils-tra